// CHECKED:

export type MessageType =
  | 'AUDIO'
  | 'CONTACTS'
  | 'DOCUMENT'
  | 'IMAGE'
  | 'INTERACTIVE_BUTTON_REPLY'
  | 'INTERACTIVE_BUTTONS'
  | 'INTERACTIVE_LIST_OPTIONS'
  | 'INTERACTIVE_LIST_SELECTION'
  | 'LOCATION'
  | 'STICKER'
  | 'TEXT'
  | 'VIDEO';
