// CHECKED:

export enum MessageTypes {
  AUDIO = 'AUDIO',
  CONTACTS = 'CONTACTS',
  DOCUMENT = 'DOCUMENT',
  IMAGE = 'IMAGE',
  INTERACTIVE_BUTTON_REPLY = 'INTERACTIVE_BUTTON_REPLY',
  INTERACTIVE_BUTTONS = 'INTERACTIVE_BUTTONS',
  INTERACTIVE_LIST_OPTIONS = 'INTERACTIVE_LIST_OPTIONS',
  INTERACTIVE_LIST_SELECTION = 'INTERACTIVE_LIST_SELECTION',
  LOCATION = 'LOCATION',
  STICKER = 'STICKER',
  TEXT = 'TEXT',
  VIDEO = 'VIDEO',
}
